#!/bin/bash

HERE=$(pwd)

ASCII_ART="$HERE/Assets/ASCII_Art.txt"

if test -e "$ASCII_ART"; then

    echo && cat "$ASCII_ART" && echo
fi

SCRIPT_PRE_PREPARE="$HERE/pre_prepare"
SCRIPT_POST_PREPARE="$HERE/post_prepare"

if test -e "$SCRIPT_PRE_PREPARE"; then

    if ! sh "$SCRIPT_PRE_PREPARE"; then

        echo "ERROR: Pre-preapre failed"
        exit 1
    fi
fi

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: The SUBMODULES_HOME is not defined !!!"
  exit 1
fi

SCRIPT="$HERE/Run/Project/open.sh"
ICONIFY="$HERE/Run/Iconic/iconify.sh"
DO_BRANDING="$HERE/Run/Iconic/do_branding.sh"

if ! test -e "$SCRIPT"; then

    echo "ERROR: Script not found at '$SCRIPT'"
    exit 1
fi

if ! test -e "$ICONIFY"; then

    echo "ERROR: Script not found at '$ICONIFY'"
    exit 1
fi

if ! test -e "$DO_BRANDING"; then

    echo "ERROR: Script not found at '$DO_BRANDING'"
    exit 1
fi

LAUNCHER_ASSET="$HERE/Assets/Launcher.svg"

if ! test -e "$LAUNCHER_ASSET"; then

    LAUNCHER_ASSET="$HERE/Assets/Launcher.png"
fi

sh "$ICONIFY"

if [ -n "$BRAND_IDE" ]; then

    echo "We are going to brand the IDE" && \
        sh "$DO_BRANDING" "$LAUNCHER_ASSET"

else

    echo "We are noy going to brand the IDE"
fi

if test -e "$SCRIPT_POST_PREPARE"; then

    if ! sh "$SCRIPT_POST_PREPARE"; then

        echo "ERROR: Post-preapre failed"
        exit 1
    fi
fi

sh "$SCRIPT"