#!/bin/bash

HERE=$(pwd)

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: The SUBMODULES_HOME is not defined !!!"
  exit 1
fi

SCRIPT_LOAD_ENV="$SUBMODULES_HOME/Software-Toolkit/Utils/Sys/environment.sh"

if ! test -e "$SCRIPT_LOAD_ENV"; then

    echo "ERROR: Script not found '$SCRIPT_LOAD_ENV'"
    exit 1
fi

# shellcheck disable=SC1090
if ! source "$SCRIPT_LOAD_ENV"; then

    if ! . "$SCRIPT_LOAD_ENV"; then

        echo "ERROR: Could not load '$SCRIPT_LOAD_ENV'"
        exit 1
    fi
fi

SCRIPT_PREPARE="$SUBMODULES_HOME/Project/prepare.sh"

if ! test  -e "$SCRIPT_PREPARE"; then

    echo "ERROR: Prepare script not found '$SCRIPT_PREPARE'"
    exit 1
fi

if ! bash "$SCRIPT_PREPARE" "$HERE"; then

    echo "ERROR: Project prepare failed"
    exit 1
fi

