#!/bin/bash

HERE=$(pwd)

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: The SUBMODULES_HOME is not defined !!!"
  exit 1
fi

SCRIPT_PREPARE="$SUBMODULES_HOME/Project/prepare.sh"
SCRIPT_INSTALL_FONTS="$HERE/Run/Install/fonts.sh"

if test -e "$SCRIPT_INSTALL_FONTS"; then

  if ! sh "$SCRIPT_INSTALL_FONTS"; then
  
    echo "ERROR: Failed to install fonts"
    exit 1
  fi
fi

if ! test  -e "$SCRIPT_PREPARE"; then

    echo "ERROR: Prepare script not found '$SCRIPT_PREPARE'"
    exit 1
fi

if ! sh "$SCRIPT_PREPARE" "$HERE"; then

    echo "ERROR: Project prepare failed"
    exit 1
fi

