#!/bin/bash

if [ -z "$SUBMODULES_HOME" ]; then

  echo "ERROR: SUBMODULES_HOME not available"
  exit 1
fi

SCRIPT_RECREATE="$SUBMODULES_HOME/recreate_current_dir.sh"

if ! test -e "$SCRIPT_RECREATE"; then

  echo "ERROR: Script not found '$SCRIPT_RECREATE'"
  exit 1
fi

bash "$SCRIPT_RECREATE"